### ISSUE TITLE
-r option fails with an permission issue

### ISSUE THREAD

**Issue by EAlf91** [zaproxy/action-api-scan#22]
**Describe the Issue**
We recently updated our action from 0.1.0 to 0.3.1 and it stopped working.

**Expected Behaviour**
If we want to create the report_html.html file with a different name and therefore supply the option -r mySpecDefinition.html we would expect to create the report from the scan with the provided filename.

**Steps to reproduce**
given this step:
```
      - name: ZAP API Scan
        uses: zaproxy/action-api-scan@v0.3.1
        with:
          target: 'https://www.myapi.de/mydocs/mySpecDefinition.json'
          cmd_options: '-r mySpecDefinition.html'
```
it fails with this error
```
ERROR [Errno 13] Permission denied: '/zap/wrk/mySpecDefinition.html'
2023-07-14 04:45:17,559 I/O error: [Errno 13] Permission denied: '/zap/wrk/mySpecDefinition.html'
Traceback (most recent call last):
  File "/zap/zap-api-scan.py", line 580, in main
    write_report(os.path.join(base_dir, report_html), zap.core.htmlreport())
  File "/zap/zap_common.py", line 564, in write_report
    with open(file_path, mode='wb') as f:
PermissionError: [Errno 13] Permission denied: '/zap/wrk/mySpecDefinition.html'
```

**Current Workaround**
as a workaround we rename the file in a step but we would expect the action to do this out of the box by providing the -r option
```
      - name: rename file
        run: mv ./report_html.html ./mySpecDefinition.html
```

**Comment by navaldewangan** [comment]
but how you can rename the file it's failing before that?
And if you add mv before then it would be not able to pick report_html.html because it's not generated.

**Comment by thc202** [comment]
The workaround is done without the `-r`, and it's being renamed after being generated.
